Repository owencooke/RQMO12, pull requests merged in 2024-03, with the labels that each got.

#25 Pong Muscle Game
  public/assets/balancebg.jpg
  src/game/scenes/Pong.js
  src/game/scenes/Preloader.js
  src/game/scenes/index.js
Labels: enhancement

#21 [UI] Dialogue Box
  index.html
  src/game/components/Dialogue.js
  src/game/components/TextBox.js
  src/game/scenes/Preloader.js
Labels: Refactoring

#33 Zebra catch
  public/assets/zebra.png
  public/assets/zebrabg.png
  src/game/scenes/Preloader.js
  src/game/scenes/ZebraCatcher.js
  src/game/scenes/index.js
  src/index.css
Labels: enhancement

#35 Added player motion in zebra catcher
  src/game/components/MyPlayer.js
  src/game/scenes/Preloader.js
  src/game/scenes/ZebraCatcher.js
Labels: bug
